### ISSUE TITLE
deb File no longer available

### ISSUE THREAD

**Issue by jonashrem** [DKFN/bunnycdn-cli#18]
The deb File is no longer available, as the domain is disabled

http://cdn.infra.tetel.in/bunnycdn-cli/nightly/deb/bnycdn_0.3.0-1_amd64.deb

![grafik](https://github.com/DKFN/bunnycdn-cli/assets/1112507/5a454f47-0933-4717-8db7-0030f9ef8440)

**Comment by DKFN** [comment]
Hi jonas,
Thanks for notifying, indeed !

I am preparing a build and setting back up the CDN again during my morning coffee.

**Comment by DKFN** [comment]
Hi again,

The file is available on anorther CDN here: https://cdn.deadlykungfu.ninja/bnycdn-cli/deb/bnycdn_0.3.0_amd64.deb
Please note that I also upgraded the CLI to NodeJS version 18 that is the current LTS version.

I am still in the process of setting up the old URL for anyone that might use it in CI/CD pipelines. And updating the docs with my personnal (and more monitored :sweat_smile: ) CDN.

Apologies for the time it took, I uploaded it with the CLI to make sure everything still worked, and I had to re-read the docs for it :)

I'll let you know when everything will be completly back to normal and close this issue.

Thanks again
